server:
  port: 3344
spring:
  application:
    name: micro-service-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Zhengfangxing/micro-service-cloud-config.git